// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package models

import validation "github.com/go-ozzo/ozzo-validation"

const (
	JwtScopes  = "Jwt.Scopes"
	UserScopes = "User.Scopes"
)

// Buzz defines model for Buzz.
type Buzz struct {
	BuzzType    string  `json:"buzzType"`
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// Couch defines model for Couch.
type Couch struct {
	FirstName  *string `json:"firstName,omitempty"`
	Id         int     `json:"id"`
	SecondName *string `json:"secondName,omitempty"`
}

// CouchPUT defines model for CouchPUT.
type CouchPUT struct {
	FirstName  string `json:"firstName"`
	SecondName string `json:"secondName"`
}

func (cp *CouchPUT) Validate() error {
	return validation.ValidateStruct(cp,
		validation.Field(&cp.FirstName, validation.Required),
		validation.Field(&cp.SecondName, validation.Required),
	)
}

// Health defines model for Health.
type Health struct {

	// app name
	App string `json:"app"`

	// app build
	Build *string `json:"build,omitempty"`

	// app tag
	Tag *string `json:"tag,omitempty"`

	// app version
	Version string `json:"version"`
}

// PaginationParam defines model for PaginationParam.
type PaginationParam struct {
	Order    *string        `json:"order,omitempty"`
	Page     int            `json:"page"`
	PageSize int            `json:"pageSize"`
	Records  []ReturnedJSON `json:"records"`
	Total    int            `json:"total"`
}

// PaginationParamCouch defines model for PaginationParamCouch.
type PaginationParamCouch struct {
	Order    *string `json:"order,omitempty"`
	Page     int     `json:"page"`
	PageSize int     `json:"pageSize"`
	Records  []Couch `json:"records"`
	Total    int     `json:"total"`
}

// ReturnedJSON defines model for ReturnedJSON.
type ReturnedJSON struct {
	BuzzType    string                 `json:"buzzType"`
	CreatedAt   int                    `json:"createdAt"`
	Description *string                `json:"description,omitempty"`
	Details     map[string]interface{} `json:"details"`
	Id          int                    `json:"id"`
	Name        string                 `json:"name"`
	UpdatedAt   *int                   `json:"updatedAt,omitempty"`
}

// GetCouchParams defines parameters for GetCouch.
type GetCouchParams struct {

	// Sorting order of records
	Order *GetCouchParamsOrder `json:"order,omitempty"`

	// Page number
	Page *float32 `json:"page,omitempty"`

	// Number of records on one page
	PageSize *float32 `json:"pageSize,omitempty"`
}

// GetCouchParamsOrder defines parameters for GetCouch.
type GetCouchParamsOrder string

// PostCouchJSONBody defines parameters for PostCouch.
type PostCouchJSONBody Couch

// PutCouchIdJSONBody defines parameters for PutCouchId.
type PutCouchIdJSONBody CouchPUT

// GetMIdBuzzParams defines parameters for GetMIdBuzz.
type GetMIdBuzzParams struct {

	// Sorting order of records
	Order *GetMIdBuzzParamsOrder `json:"order,omitempty"`

	// Page number
	Page *int `json:"page,omitempty"`

	// Number of records on one page
	PageSize *float32 `json:"pageSize,omitempty"`
}

// GetMIdBuzzParamsOrder defines parameters for GetMIdBuzz.
type GetMIdBuzzParamsOrder string

// PostMIdBuzzJSONBody defines parameters for PostMIdBuzz.
type PostMIdBuzzJSONBody Buzz

// PutMIdBuzzIdJSONBody defines parameters for PutMIdBuzzId.
type PutMIdBuzzIdJSONBody Buzz

// PostCouchJSONRequestBody defines body for PostCouch for application/json ContentType.
type PostCouchJSONRequestBody PostCouchJSONBody

// PutCouchIdJSONRequestBody defines body for PutCouchId for application/json ContentType.
type PutCouchIdJSONRequestBody PutCouchIdJSONBody

// PostMIdBuzzJSONRequestBody defines body for PostMIdBuzz for application/json ContentType.
type PostMIdBuzzJSONRequestBody PostMIdBuzzJSONBody

// PutMIdBuzzIdJSONRequestBody defines body for PutMIdBuzzId for application/json ContentType.
type PutMIdBuzzIdJSONRequestBody PutMIdBuzzIdJSONBody
